## Data Processing - regression

### # Get Data

In [1]:
import numpy as np

loaded_dataset = np.load('D:/KAISTmicrodegree/5_캡스톤/플젝/[Microdegree] Hypotension/data_reg/all_reg_arr.npz', allow_pickle = True)

# x_arr = loaded_dataset['x_arr']
y_arr = loaded_dataset['y_arr']
c_arr = loaded_dataset['c_arr']
# a_arr = loaded_dataset['a_arr']

x_arr = loaded_dataset['x_arr'][:,:,1]

# # y_arr 각 값의 개수 찾기
# unique_values, counts = np.unique(y_arr, return_counts=True)
# unique_counts = dict(zip(unique_values, counts))

print(loaded_dataset)

NpzFile 'D:/KAISTmicrodegree/5_캡스톤/플젝/[Microdegree] Hypotension/data_reg/all_reg_arr.npz' with keys: x_arr, y_arr, c_arr, a_arr


In [4]:
# import numpy as np

# loaded_dataset = np.load('D:/KAISTmicrodegree/5_캡스톤/플젝/[Microdegree] Hypotension/data_clf/all_clf_arr.npz', allow_pickle = True)

# clf_x_arr = loaded_dataset['x_arr']
# print(loaded_dataset)

# ##  biosignal data

# # patient count
# print(len(clf_x_arr)) # 528371
# print(clf_x_arr.shape) # (528371, 3000, 3)
# print(type(clf_x_arr))
# # print(clf_x_arr)
# print()
# # length of each signals (ECG, PPG, CO2)
# print(len(clf_x_arr[0])) # 3000
# print(clf_x_arr[0].shape) # (3000, 3)
# print(clf_x_arr[0])

# # PPG
# # print(len(clf_x_arr[:,:,1])) # 528371
# # print(clf_x_arr[:,:,1].shape) # (528371, 3000)
# # print(clf_x_arr[:,:,1])

528371
(528371, 3000, 3)
<class 'numpy.ndarray'>

3000
(3000, 3)
[[-2.88494006e-02  3.12346001e+01  1.39999998e+00]
 [-2.88494006e-02  3.12346001e+01  1.29999995e+00]
 [-2.88494006e-02  3.12346001e+01  1.29999995e+00]
 ...
 [-2.88494006e-02  4.26890984e+01  1.50000000e+00]
 [-2.88494006e-02  4.54539986e+01  1.50000000e+00]
 [-2.88494006e-02  4.90088005e+01  1.50000000e+00]]


In [2]:
##  biosignal data

# patient count
print(len(x_arr)) # 528371
print(x_arr.shape) # (528371, 3000, 3)
print(type(x_arr))
print(x_arr)
print()
# length of each signals (ECG, PPG, CO2)
print(len(x_arr[0])) # 3000
print(x_arr[0].shape) # (3000, 3)
print(x_arr[0])

# PPG
# print(len(x_arr[:,:,1])) # 528371
# print(x_arr[:,:,1].shape) # (528371, 3000)
# print(x_arr[:,:,1])

509281
(509281, 3000)
<class 'numpy.ndarray'>
[[32.02460098 32.41960144 32.02460098 ... 45.45399857 44.26900101
  44.26900101]
 [37.94929886 37.5542984  37.15940094 ... 44.26900101 44.26900101
  43.47909927]
 [36.76440048 38.34429932 39.52930069 ... 40.31919861 40.31919861
  40.71419907]
 ...
 [38.73929977 38.73929977 38.73929977 ... 39.52930069 39.52930069
  39.13430023]
 [41.89920044 42.68909836 43.08409882 ... 39.52930069 39.13430023
  39.13430023]
 [37.94929886 37.94929886 37.94929886 ... 38.34429932 37.94929886
  38.34429932]]

3000
(3000,)
[32.02460098 32.41960144 32.02460098 ... 45.45399857 44.26900101
 44.26900101]


In [7]:
## ground truth (0 or 1 or Nan)

print(len(y_arr)) # 528371
print(y_arr[:100])
y_values, y_counts = np.unique(y_arr, return_counts=True)
y_dict = dict(zip(y_values, y_counts))
# print(y_values, y_counts)
# print(y_dict)
# print(len(y_dict.keys()))
# print(sum((y_dict.values())))

509281
[73. 73. 70. 70. 62. 58. 52. 59. 63. 65. 66. 67. 69. 80. 86. 98. 96. 95.
 93. 98. 94. 95. 99. 94. 93. 95. 94. 93. 90. 94. 93. 94. 94. 94. 95. 91.
 91. 91. 92. 93. 92. 93. 95. 96. 95. 59. 93. 91. 89. 88. 91. 94. 88. 90.
 95. 96. 90. 89. 85. 86. 86. 88. 89. 94. 94. 73. 95. 94. 93. 93. 92. 93.
 92. 93. 91. 90. 92. 93. 90. 90. 90. 90. 91. 91. 92. 90. 92. 94. 94. 94.
 95. 96. 95. 95. 92. 60. 92. 87. 91. 92.]


In [8]:
## case ID 

print(len(c_arr)) # 528371
print(c_arr[:100])
c_values, c_counts = np.unique(c_arr, return_counts=True)
c_dict = dict(zip(c_values, c_counts))
print(c_dict)
print(len(c_dict.keys())) # 3376
print(sum((c_dict.values()))) # 528371

509281
[2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072
 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072
 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072
 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072
 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072
 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072
 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072 2072
 2072 2072]
{1: 138, 4: 250, 7: 184, 10: 283, 13: 98, 16: 153, 17: 255, 19: 398, 20: 370, 22: 185, 24: 45, 25: 193, 26: 105, 27: 224, 28: 373, 29: 279, 31: 114, 34: 357, 38: 132, 43: 179, 44: 174, 46: 110, 49: 104, 50: 200, 51: 80, 52: 180, 58: 175, 59: 10, 60: 165, 61: 99, 64: 170, 65: 143, 66: 108, 67: 99, 68: 65, 69: 65, 70: 149, 74: 209, 75: 327, 77: 125, 79: 283, 83: 243, 84: 230, 87: 140, 89: 275, 92: 38, 93: 25, 94: 410, 96: 582, 97: 149, 98: 70, 101: 149, 103: 120, 104: 150, 105: 218

In [5]:
# ## patient meta data

# import random
# print(len(a_arr))
# for _ in range(10):
#     print(a_arr[random.randint(0, len(y_arr))])

509281
[[58.0 'M' 65.75 166.6 2.0]]
[[65.0 'F' 84.85 157.9 nan]]
[[57.0 'F' 50.05 151.2 2.0]]
[[65.0 'M' 62.9 169.6 2.0]]
[[69.0 'M' 66.5 169.6 3.0]]
[[62.0 'M' 66.8 173.3 2.0]]
[[68.0 'M' 55.7 163.6 2.0]]
[[76.0 'M' 78.8 164.8 2.0]]
[[62.0 'M' 74.4 172.7 2.0]]
[[55.0 'F' 60.0 154.9 2.0]]


In [5]:
import pickle

with open('D:/KAISTmicrodegree/5_캡스톤/플젝/[Microdegree] Hypotension/data_reg/reg_train_valid_test_caseids.pkl', 'rb') as f:
    caseids_train, caseids_valid, caseids_test = pickle.load(f)

print(len(caseids_train), caseids_train)
print(len(caseids_valid), caseids_valid)
print(len(caseids_test), caseids_test)
print()
caseids_total = len(caseids_train)+len(caseids_valid)+len(caseids_test)
print("Total caseids : ",  caseids_total)
print("- train caseids : ",  len(caseids_train), "(%.2f)" %(len(caseids_train)/caseids_total*100))
print("- valid caseids : ",  len(caseids_valid), "(%.2f)" %(len(caseids_valid)/caseids_total*100))
print("- test caseids : ",  len(caseids_test), "(%.2f)" %(len(caseids_test)/caseids_total*100))

1892 [2562, 2566, 2568, 2569, 2572, 2575, 2576, 2578, 2580, 2583, 2584, 2585, 2587, 2589, 2590, 2593, 2594, 2596, 2597, 2601, 2602, 2605, 2607, 2609, 2611, 2612, 2613, 2616, 2618, 2619, 2622, 2624, 2628, 2630, 2631, 2632, 2637, 2639, 2641, 2644, 2645, 2646, 2648, 2651, 2652, 2655, 2656, 2657, 2658, 2662, 2663, 2664, 2665, 2667, 2670, 2671, 2672, 2673, 2674, 2676, 2678, 2680, 2687, 2688, 2690, 2693, 2695, 2697, 2698, 2699, 2701, 2703, 2705, 2706, 2712, 2713, 2716, 2717, 2720, 2721, 2724, 2727, 2732, 2733, 2735, 2736, 2740, 2741, 2742, 2744, 2746, 2747, 2749, 2750, 2751, 2753, 2755, 2760, 2762, 2763, 2764, 2765, 2766, 2769, 2774, 2775, 2776, 2777, 2778, 2779, 2781, 2783, 2785, 2788, 2795, 2799, 2800, 2801, 2803, 2804, 2806, 2807, 2808, 2809, 2815, 2819, 2820, 2823, 2824, 2827, 2828, 2829, 2830, 2835, 2836, 2839, 2845, 2847, 2848, 2849, 2850, 2851, 2854, 2858, 2859, 2860, 2861, 2863, 2864, 2868, 2870, 2871, 2876, 2877, 2883, 2888, 2889, 2890, 2891, 2895, 2900, 2903, 2905, 2906, 2909, 2910

### # check valid / train / test data portion

In [15]:
count_datas_train = {}
count_datas_valid = {}
count_datas_test = {}
count_datas_total = {}

for index, id in enumerate(c_arr):
    flag = False
    if id in caseids_train:
        if id not in count_datas_train:
            count_datas_train[id] = 0
        count_datas_train[id] += 1
        flag = True
    elif id in caseids_valid:
        if id not in count_datas_valid:
            count_datas_valid[id] = 0
        count_datas_valid[id] += 1
        flag = True
    elif id in caseids_test:
        if id not in count_datas_test:
            count_datas_test[id] = 0
        count_datas_test[id] += 1
        flag = True
    
    if flag:
        if id not in count_datas_total:
            count_datas_total[id] = 0
        count_datas_total[id] += 1

print(count_datas_total)
print(count_datas_train)
print(count_datas_valid)
print(count_datas_test)
print()
print("Total caseids / data count : %d / %d" %(len(count_datas_total.keys()), sum(count_datas_total.values())))
print("- train caseids / data count : %d / %d (%.2f)" %(len(count_datas_train.keys()), sum(count_datas_train.values()), sum(count_datas_train.values())/sum(count_datas_total.values())*100))
print("- valid caseids / data count : %d / %d (%.2f)" %(len(count_datas_valid.keys()), sum(count_datas_valid.values()), sum(count_datas_valid.values())/sum(count_datas_total.values())*100))
print("- test caseids / data count : %d / %d (%.2f)" %(len(count_datas_test.keys()), sum(count_datas_test.values()), sum(count_datas_test.values())/sum(count_datas_total.values())*100))
print("- (missing caseids / data count) : %d / %d" %(len(c_dict.keys())-len(count_datas_total.keys()), sum(c_dict.values())-sum(count_datas_total.values())))
print()

{2072: 159, 1145: 225, 2510: 40, 3928: 49, 435: 125, 831: 120, 6195: 193, 4913: 110, 3348: 248, 1324: 145, 6071: 268, 3125: 215, 742: 208, 2241: 109, 4976: 192, 800: 155, 5116: 35, 5524: 250, 10: 283, 3843: 255, 4569: 30, 3517: 91, 1043: 68, 5508: 189, 1585: 50, 3530: 35, 4048: 35, 5851: 130, 2903: 30, 5393: 124, 3307: 165, 2220: 266, 952: 35, 22: 185, 721: 154, 2895: 69, 4872: 296, 629: 421, 6067: 58, 2900: 43, 4270: 145, 6086: 180, 4177: 35, 92: 38, 1761: 234, 1281: 64, 4732: 205, 3186: 269, 468: 265, 3840: 145, 851: 254, 865: 147, 3203: 231, 2596: 80, 790: 28, 3218: 80, 5126: 205, 5394: 62, 748: 238, 5308: 175, 5711: 33, 1752: 495, 4286: 213, 2678: 95, 626: 450, 363: 240, 4175: 467, 5810: 100, 7: 184, 5229: 150, 4020: 100, 3878: 205, 1714: 164, 1566: 140, 2987: 80, 2287: 120, 4461: 388, 3121: 317, 1325: 321, 2850: 185, 505: 152, 1636: 95, 3712: 103, 576: 100, 5694: 220, 1182: 169, 2413: 20, 1474: 130, 1613: 70, 4820: 204, 3628: 70, 1599: 260, 6262: 55, 2258: 160, 2194: 285, 1886: 11

In [16]:
for id, count in count_datas_total.items():
    assert count == c_dict[id], "beep !"

### # check nan in x_arr

In [19]:
# count nans in arrs(3000) of x_arr(509281)
import collections

def check_nan_in_x_arr(arr):
    count = 0
    check_nan = np.isnan(arr)
    # print(check_nan)
    # print(collections.Counter(check_nan)[True])
    for index, boolen in enumerate(check_nan):
        if boolen == True:
            count += 1
    return count, collections.Counter(check_nan)[True]

total_nan_counts = 0
arr_nan_counts = 0
some_nans = []
all_nans = []
# some_nans = {}
# all_nans = {}
for index, arr in enumerate(x_arr):
    # count, nans = check_nan_in_x_arr(arr)
    count, collections_count = check_nan_in_x_arr(arr)
    assert count == collections_count, "counting error! (%d - %d, %d)" %(index, count, collections_count)
    if count > 0:
        arr_nan_counts += 1
        if count == len(arr): # 3000
            all_nans.append((index, count, collections_count))
            # all_nans[index] = count
        else:
            some_nans.append((index, count, collections_count))
            # some_nans[index] = count
        # print(index, count)
        # print(nans)
    total_nan_counts += count

print("total nans in x_arr : ", total_nan_counts)
print("arr with nans : ", arr_nan_counts)
print("- some of 3000 are nans :", len(some_nans), some_nans)
print("- all of 3000 are nans :", len(all_nans), all_nans)
# print("- some of 3000 are nans :", len(some_nans.keys()), sum(some_nans.values()), some_nans)
# print("- all of 3000 are nans :", len(all_nans.keys()), sum(all_nans.values()), all_nans)

# total nans in x_arr :  18222051
# arr with nans :  6984
# - some of 3000 are nans : 1318 
# - all of 3000 are nans : 5666

total nans in x_arr :  18222051
arr with nans :  6984
- some of 3000 are nans : 1318 [(252, 341, 341), (1607, 1504, 1504), (1811, 1612, 1612), (3282, 12, 12), (3339, 2812, 2812), (4612, 1443, 1443), (4956, 71, 71), (5056, 1364, 1364), (6655, 169, 169), (7473, 1526, 1526), (7477, 517, 517), (7607, 967, 967), (7609, 1, 1), (7611, 2, 2), (7655, 228, 228), (7836, 2012, 2012), (9212, 2038, 2038), (9491, 72, 72), (9492, 139, 139), (9494, 439, 439), (9495, 223, 223), (9497, 81, 81), (9501, 441, 441), (9502, 183, 183), (9503, 441, 441), (9504, 760, 760), (9505, 368, 368), (9506, 1305, 1305), (9508, 368, 368), (9513, 1248, 1248), (9514, 145, 145), (9516, 2456, 2456), (9594, 1712, 1712), (10556, 2854, 2854), (10620, 1140, 1140), (10919, 297, 297), (10933, 1710, 1710), (11176, 722, 722), (11480, 1500, 1500), (12979, 1009, 1009), (13999, 791, 791), (14246, 71, 71), (14366, 962, 962), (14390, 2325, 2325), (14488, 206, 206), (15111, 53, 53), (15410, 398, 398), (16134, 379, 379), (16653, 945, 945), (

In [20]:
# data which has 'nan' value (each data has 3000 values)
nan_arrs = some_nans + all_nans # 1372 + 11572 =12944
print("nan signal datas (arr index counts):\n ", len(nan_arrs), nan_arrs)

nan_ids = {}
for (index, count, collections_count) in nan_arrs:
    if c_arr[index] not in nan_ids:
        nan_ids[c_arr[index]] = []
    nan_ids[c_arr[index]].append((index, count, collections_count))
print("nan ids (id : x_arr index, count1, count2) :\n ", len(nan_ids), nan_ids)
nan_data_per_id = {}
for id, value in nan_ids.items():
    nan_data_per_id[id] = 0
    nan_data_per_id[id] = len(value)
nan_data_per_id = dict(sorted(nan_data_per_id.items(), key = lambda x:x[1], reverse=True))
print("nan data per id (id : count) :\n ", len(nan_data_per_id), sum(nan_data_per_id.values()), nan_data_per_id)  
print()

train_nans = {}
# train_all_nans = {}
for id in caseids_train:
    if id in list(nan_ids.keys()):
        # if nan_ids[id][0] == 3000:
        #     train_all_nans[id] = (nan_ids[id][0], nan_ids[id][1])
        # else:
        #     train_nans[id] = (nan_ids[id][0], nan_ids[id][1])
        train_nans[id] = nan_ids[id]
# print(len(train_all_nans), train_all_nans)

valid_nans = {}
# valid_all_nans = {}
for id in caseids_valid:
    if id in list(nan_ids.keys()):
        # if nan_ids[id][0] == 3000:
        #     valid_all_nans[id] = (nan_ids[id][0], nan_ids[id][1])
        # else:
        #     valid_nans[id] = (nan_ids[id][0], nan_ids[id][1])
        valid_nans[id] = nan_ids[id]
# print(len(valid_all_nans), valid_all_nans)

test_nans = {}
# test_all_nans = {}
for id in caseids_test:
    if id in list(nan_ids.keys()):
        # if nan_ids[id][0] == 3000:
        #     test_all_nans[id] = (nan_ids[id][0], nan_ids[id][1])
        # else:
        #     test_nans[id] = (nan_ids[id][0], nan_ids[id][1])
        test_nans[id] = nan_ids[id]
# print(len(test_all_nans), test_all_nans)

print("nan ids in x_arr : %d" %len(nan_data_per_id))
print("nan ids in caseids_total : %d" %(len(train_nans)+len(valid_nans)+len(test_nans)))
print("(Excluded from train/valid/test) : ", len(nan_data_per_id) - (len(train_nans)+len(valid_nans)+len(test_nans)))
print()
print("total nan ids (%.2f) : %d" %((len(train_nans)+len(valid_nans)+len(test_nans))/caseids_total*100, len(train_nans)+len(valid_nans)+len(test_nans)))
print("- train_nans (%.2f) : " %(len(train_nans)/len(caseids_train)*100))
print("  ", len(train_nans), train_nans)
print("- valid_nans (%.2f) : " %(len(valid_nans)/len(caseids_valid)*100))
print("  ", len(valid_nans), valid_nans)
print("- test_nans (%.2f): " %(len(test_nans)/len(caseids_test)*100))
print("  ", len(test_nans), test_nans)

nan signal datas (arr index counts):
  6984 [(252, 341, 341), (1607, 1504, 1504), (1811, 1612, 1612), (3282, 12, 12), (3339, 2812, 2812), (4612, 1443, 1443), (4956, 71, 71), (5056, 1364, 1364), (6655, 169, 169), (7473, 1526, 1526), (7477, 517, 517), (7607, 967, 967), (7609, 1, 1), (7611, 2, 2), (7655, 228, 228), (7836, 2012, 2012), (9212, 2038, 2038), (9491, 72, 72), (9492, 139, 139), (9494, 439, 439), (9495, 223, 223), (9497, 81, 81), (9501, 441, 441), (9502, 183, 183), (9503, 441, 441), (9504, 760, 760), (9505, 368, 368), (9506, 1305, 1305), (9508, 368, 368), (9513, 1248, 1248), (9514, 145, 145), (9516, 2456, 2456), (9594, 1712, 1712), (10556, 2854, 2854), (10620, 1140, 1140), (10919, 297, 297), (10933, 1710, 1710), (11176, 722, 722), (11480, 1500, 1500), (12979, 1009, 1009), (13999, 791, 791), (14246, 71, 71), (14366, 962, 962), (14390, 2325, 2325), (14488, 206, 206), (15111, 53, 53), (15410, 398, 398), (16134, 379, 379), (16653, 945, 945), (16927, 1, 1), (17518, 20, 20), (17994, 10

### # process x_arr data (get rid of nan)

In [21]:
# change x_arr nan -> mean of previous values
some_nans_index = list(map(lambda x : x[0], some_nans))
print(len(some_nans_index), some_nans_index)

all_nans_index = list(map(lambda x : x[0], all_nans))
print(len(all_nans_index), all_nans_index)

def process_all_nan_arr(arr):
    arr = np.zeros(len(arr))
    return arr

def process_some_nan_arr(arr):
    check_nan = np.isnan(arr)
    for index, boolen in enumerate(check_nan):
        if boolen == True:
            if index == 0:
                arr[index] = 0
            else:
                arr[index] = np.mean(arr[:index])

for index, arr in enumerate(x_arr):
    if index in all_nans_index:
        x_arr[index] = process_all_nan_arr(arr)
        assert np.count_nonzero(x_arr[index]) == 0, '(%d) need all zero for all_nans_index !' %(index)
    elif index in some_nans_index:
        process_some_nan_arr(arr)
        assert collections.Counter(np.isnan(x_arr[index]))[True] == 0, '(%d) there is nan in some_nans_index !' %(index)

1318 [252, 1607, 1811, 3282, 3339, 4612, 4956, 5056, 6655, 7473, 7477, 7607, 7609, 7611, 7655, 7836, 9212, 9491, 9492, 9494, 9495, 9497, 9501, 9502, 9503, 9504, 9505, 9506, 9508, 9513, 9514, 9516, 9594, 10556, 10620, 10919, 10933, 11176, 11480, 12979, 13999, 14246, 14366, 14390, 14488, 15111, 15410, 16134, 16653, 16927, 17518, 17994, 18500, 18706, 18977, 19306, 19616, 20998, 21667, 21880, 21947, 22389, 22931, 23371, 23396, 23653, 23654, 23655, 23749, 23824, 23835, 23836, 23837, 23851, 24012, 24593, 25125, 25191, 26133, 26450, 26619, 27849, 27955, 29025, 29225, 29236, 29238, 29651, 29790, 29943, 30132, 30911, 31212, 31615, 31782, 32625, 33471, 33489, 33524, 33549, 33575, 34785, 34788, 35270, 35382, 35590, 35744, 35820, 35862, 36567, 37668, 37889, 38137, 38468, 38709, 38812, 38828, 40422, 40542, 40569, 40572, 40583, 41935, 41969, 43268, 43329, 44531, 45080, 45476, 46092, 46517, 46546, 46553, 46607, 47569, 47773, 47922, 47932, 47946, 50088, 50500, 51020, 51914, 52060, 52177, 52599, 53243,

In [22]:
# double check on x_arr values (nan)
for index, arr in enumerate(x_arr):
    # count, nans = check_nan_in_x_arr(arr)
    count, collections_count = check_nan_in_x_arr(arr)
    assert count == 0, "(%d, %d) there's stil nan in x_arr !" %(index, count)
print(len(x_arr))

509281


In [24]:
# double check on x_arr values (missing)
for index, arr in enumerate(x_arr):
    # count, nans = check_nan_in_x_arr(arr)
    assert len(arr) == 3000, "(%d, %d) something's deleted !" %(index, len(arr))
assert x_arr.shape == (len(x_arr), 3000), "something's deleted !" # (509281, 3000)

### # split and save train / valid / test

In [25]:
train_datas = []
train_labels = []
for id in caseids_train:
    train_datas.append(x_arr[id])
    train_labels.append(y_arr[id])
with open('../data_reg/train_reg_x_cleaned.pkl', 'wb') as f:
    pickle.dump(train_datas, f)
with open('../data_reg/train_reg_y_cleaned.pkl', 'wb') as f:
    pickle.dump(train_labels, f)

valid_datas = []
valid_labels = []
for id in caseids_valid:
    valid_datas.append(x_arr[id])
    valid_labels.append(y_arr[id])
with open('../data_reg/valid_reg_x_cleaned.pkl', 'wb') as f:
    pickle.dump(valid_datas, f)
with open('../data_reg/valid_reg_y_cleaned.pkl', 'wb') as f:
    pickle.dump(valid_labels, f)

test_datas = []
test_labels = []
for id in caseids_test:
    test_datas.append(x_arr[id])
    test_labels.append(y_arr[id])
with open('../data_reg/test_reg_x_cleaned.pkl', 'wb') as f:
    pickle.dump(test_datas, f)
with open('../data_reg/test_reg_y_cleaned.pkl', 'wb') as f:
    pickle.dump(test_labels, f)
print(">> Done spliting datas !")
print()


with open('../data_reg/train_reg_x_cleaned.pkl', 'rb') as f:
    train_x_cleaned = pickle.load(f)
with open('../data_reg/train_reg_y_cleaned.pkl', 'rb') as f:
    train_y_cleaned = pickle.load(f)   
print(type(train_x_cleaned), type(train_y_cleaned))
print(len(train_x_cleaned), len(train_y_cleaned))
print(len(train_x_cleaned[0]), train_x_cleaned[0])
print(train_y_cleaned[:20])

print()
with open('../data_reg/valid_reg_x_cleaned.pkl', 'rb') as f:
    valid_x_cleaned = pickle.load(f)
with open('../data_reg/valid_reg_y_cleaned.pkl', 'rb') as f:
    valid_y_cleaned = pickle.load(f)   
print(type(valid_x_cleaned), type(valid_y_cleaned))
print(len(valid_x_cleaned), len(valid_y_cleaned))
print(len(valid_x_cleaned[0]), valid_x_cleaned[0])
print(valid_y_cleaned[:20])

print()
with open('../data_reg/test_reg_x_cleaned.pkl', 'rb') as f:
    test_x_cleaned = pickle.load(f)
with open('../data_reg/test_reg_y_cleaned.pkl', 'rb') as f:
    test_y_cleaned = pickle.load(f)   
print(type(test_x_cleaned), type(test_y_cleaned))
print(len(test_x_cleaned), len(test_y_cleaned))
print(len(test_x_cleaned[0]), test_x_cleaned[0])
print(test_y_cleaned[:20])

# Total caseids / data count : 3153 / 505529
# - train caseids / data count : 1892 / 304766 (60.29)
# - valid caseids / data count : 631 / 100446 (19.87)
# - test caseids / data count : 630 / 100317 (19.84)

>> Done spliting datas !

<class 'list'> <class 'list'>
1892 1892
3000 [35.97439957 36.36940002 36.76440048 ... 45.45399857 48.61389923
 52.95869827]
[61.0, 64.0, 64.0, 65.0, 79.0, 102.0, 94.0, 94.0, 193.0, 79.0, 77.0, 77.0, 73.0, 70.0, 70.0, 73.0, 73.0, 96.0, 101.0, 189.0]

<class 'list'> <class 'list'>
631 631
3000 [29.25970078 28.86470032 28.07480049 ... 26.09980011 26.09980011
 26.09980011]
[60.0, 55.0, 52.0, 66.0, 66.0, 69.0, 76.0, 78.0, 85.0, 87.0, 97.0, 93.0, 93.0, 91.0, 97.0, 99.0, 96.0, 90.0, 84.0, 83.0]

<class 'list'> <class 'list'>
630 630
3000 [37.94929886 37.5542984  37.15940094 ... 44.26900101 44.26900101
 43.47909927]
[73.0, 62.0, 59.0, 66.0, 80.0, 96.0, 95.0, 98.0, 99.0, 93.0, 95.0, 94.0, 93.0, 90.0, 94.0, 94.0, 95.0, 92.0, 96.0, 95.0]
