### # load dataset

#### Exclude
- case 1. 한 segment 내 0 이하인 값들, np.nan 이 있는 경우 제외
- case 2. waveform 의 peak 탐색 후 한 segment 내 peak의 수가 10개 이하인 경우 제외
- case 3. segment 내 beat의 길이들의 평균을 이용하여 불규칙적인 파형들은 제외
- case 4. segment 내 beat 들의 상관관계가 0.9 미만인 경우 제외

In [1]:
import psutil

psutil.virtual_memory()

svmem(total=8499666944, available=1607344128, percent=81.1, used=6892322816, free=1607344128)

In [2]:
import numpy as np

loaded_dataset = np.load('D:/KAISTmicrodegree/5_캡스톤/플젝/[Microdegree] Hypotension/data_clf/all_clf_arr.npz', allow_pickle = True)
# x_arr = loaded_dataset['x_arr']
x_arr = loaded_dataset['x_arr'][:,:,1]
y_arr = loaded_dataset['y_arr']
c_arr = loaded_dataset['c_arr']
# a_arr = loaded_dataset['a_arr']

print(loaded_dataset)
print()

print(len(x_arr)) # 528371
print(x_arr.shape) # (528371, 3000) (528371, 3000, 3)
print(type(x_arr)) # <class 'numpy.ndarray'>
# print(x_arr[0])
print()

print(len(y_arr)) # 528371
print(y_arr.shape) # (528371, )
print(type(y_arr)) # <class 'numpy.ndarray'>
# print(y_arr[:100])
print()

print(len(c_arr)) # 528371
print(c_arr.shape) # (528371, )
print(type(c_arr)) # <class 'numpy.ndarray'>
# print(c_arr[:100])

NpzFile 'D:/KAISTmicrodegree/5_캡스톤/플젝/[Microdegree] Hypotension/data_clf/all_clf_arr.npz' with keys: x_arr, y_arr, c_arr, a_arr

528371
(528371, 3000)
<class 'numpy.ndarray'>

528371
(528371,)
<class 'numpy.ndarray'>

528371
(528371,)
<class 'numpy.ndarray'>


In [3]:
psutil.virtual_memory()

svmem(total=8499666944, available=394002432, percent=95.4, used=8105664512, free=394002432)

### # process y_arr (remove nan)

In [3]:
x_arr = x_arr[~np.isnan(y_arr)]
c_arr = c_arr[~np.isnan(y_arr)]
# a_arr = a_arr[~np.isnan(y_arr)]
y_arr = y_arr[~np.isnan(y_arr)]

# # x_arr = x_arr[:,:,1].reshape(-1, 1, 3000) # pytorch 를 위한 shape 으로 변경 
# x_arr = x_arr.reshape(-1, 1, 3000) # pytorch 를 위한 shape 으로 변경 

# # remove index of y_arr == nan
# cleaned_x_arr = []
# cleaned_y_arr = []
# cleaned_c_arr = []
# isnan_y_arr = ~np.isnan(y_arr)
# for index, label in enumerate(isnan_y_arr):
# # for index, label in enumerate(y_arr):
#     if label:
#     # if label in [0, 1]:
#         cleaned_x_arr.append(x_arr[index])
#         cleaned_y_arr.append(y_arr[index])
#         cleaned_c_arr.append(c_arr[index])

# # cleaned_x_arr = np.array(cleaned_x_arr)
# # cleaned_y_arr = np.array(cleaned_y_arr)
# # cleaned_c_arr = np.array(cleaned_c_arr)

In [4]:
print(len(x_arr)) # 330619
print(x_arr.shape) # (330619, 3000)
print(type(x_arr))
# print(x_arr[0])
print()

print(len(y_arr)) # 330619
print(y_arr.shape) # (330619,)
print(type(y_arr))
# print(y_arr[:100])
print()

print(len(c_arr)) # 330619
print(c_arr.shape) # (330619,)
print(type(c_arr))
# print(c_arr[:100])

330619
(330619, 3000)
<class 'numpy.ndarray'>

330619
(330619,)
<class 'numpy.ndarray'>

330619
(330619,)
<class 'numpy.ndarray'>


### # process x_arr (remove nan and <= 0)

In [5]:
# def fill_2d_missing_with_previous(arr): # 결측값 이전 값으로 대체 
#     # 결측값이 아닌 값들의 위치를 찾음
#     valid = np.isnan(arr) == False
    
#     # 누적 최대값을 사용하여 각 위치에서 마지막으로 관찰된 유효한 값을 채움
#     filled = np.maximum.accumulate(valid, axis=1)

#     # np.where를 사용하여 유효한 값과 결측값의 위치에 따라 값을 선택
#     return np.where(filled, arr, np.nan)

# x_arr = fill_2d_missing_with_previous(x_arr)

# erase index of x_arr != nan and x_arr > 0
idx = []
for i in range(len(x_arr)):
    if (np.isnan(x_arr[i]).sum() == 0)&(np.min(x_arr[i]) > 0):
        idx.append(i)
        
x_arr = x_arr[idx].astype(float)
y_arr = y_arr[idx].astype(float)
c_arr = c_arr[idx]

# xy_cleaned_x_arr = []
# xy_cleaned_y_arr = []
# xy_cleaned_c_arr = []
# for index in idx:
#     xy_cleaned_x_arr.append(cleaned_x_arr[index])
#     xy_cleaned_y_arr.append(cleaned_y_arr[index])
#     xy_cleaned_c_arr.append(cleaned_c_arr[index])

# xy_cleaned_x_arr = np.array(xy_cleaned_x_arr)
# xy_cleaned_y_arr = np.array(xy_cleaned_y_arr)
# xy_cleaned_c_arr = np.array(xy_cleaned_c_arr)

In [6]:
print(len(x_arr)) # 312462
print(x_arr.shape) # (312462, 3000)
print(type(x_arr))
# print(x_arr[0])
print()

print(len(y_arr)) # 312462
print(y_arr.shape) # (312462,)
print(type(y_arr))
# print(y_arr[:100])
print()

print(len(c_arr)) # 312462
print(c_arr.shape) # (312462,)
print(type(c_arr))
# print(c_arr[:100])

312462
(312462, 3000)
<class 'numpy.ndarray'>

312462
(312462,)
<class 'numpy.ndarray'>

312462
(312462,)
<class 'numpy.ndarray'>


### # preprocess x_arr
- (peak) remove num peak <= 10
- (beat) remove if average of beats is irregular
- (beat) remove if correlation of beats < 0.9
- (reference : https://github.com/vitaldb/pyvital/blob/master/pyvital/filters/pleth_dpop.py)

In [9]:
# !pip install pyvital

In [12]:
from pyvital import arr

def process_beat(seg):
    data = arr.interp_undefined(seg.flatten())

    # beat detection
    minlist, maxlist = arr.detect_peaks(data, 100)
    maxlist = maxlist[1:]

    # caseid = caseid.replace('.vital', '')

    # beat lengths
    beatlens = []
    beats = []
    beats_128 = []
    beats_128_valid = []
    for j in range(0, len(minlist)-1):
        beatlen = minlist[j+1] - minlist[j]  # in samps
        beatlens.append(beatlen)
        beat = data[minlist[j]:minlist[j+1]]
        beats.append(beat)
        resampled = arr.resample(beat, 100)  # 임시로 100
        beats_128.append(resampled)
        beats_128_valid.append(resampled)

    # 2. (beat) remove if average of beats is irregular
    avgbeat = np.array(beats_128_valid).mean(axis=0)
    nucase_mbeats = len(maxlist)

    # 1. (peak) remove num peak <= 10
    if nucase_mbeats < 10:
        # print('nucase_mbeats < 4')
        return 0, []
    meanlen = np.mean(beatlens)
    stdlen = np.std(beatlens)
    if stdlen > meanlen * 0.2: # irregular rhythm
        # print('irregular rhythm')
        return 0, []
    
    # 3. (beat) remove if correlation of beats < 0.9
    beatstds = []
    for i in range(len(beats_128)):
        if np.corrcoef(avgbeat, beats_128[i])[0, 1] < 0.9:
            # print('corrcoef')
            return 0, []
        else:
            beatstds.append(np.std(beats[i]))
        return np.mean(beatstds), []

case_mstds_list = []

for i in range(len(x_arr)):
    mstd_seg, _ = process_beat(x_arr[i].reshape(-1, 1))
    case_mstds_list.append(mstd_seg)
case_mask = list(np.where(np.array(np.squeeze(case_mstds_list)) > 0)[0])

x_arr = x_arr[case_mask]
y_arr = y_arr[case_mask]
c_arr = c_arr[case_mask]

In [13]:
print(len(x_arr)) # 191453
print(x_arr.shape) # (191453, 3000)
print(type(x_arr))
# print(x_arr[0])
print()

print(len(y_arr)) # 191453
print(y_arr.shape) # (191453,)
print(type(y_arr))
# print(y_arr[:100])
print()

print(len(c_arr)) # 191453
print(c_arr.shape) # (191453,)
print(type(c_arr))
# print(c_arr[:100])

191453
(191453, 3000)
<class 'numpy.ndarray'>

191453
(191453,)
<class 'numpy.ndarray'>

191453
(191453,)
<class 'numpy.ndarray'>


### # (check out if data processed correctly)

In [14]:
import collections

def check_nan_in_x_arr(arr):
    count = 0
    check_nan = np.isnan(arr)
    # print(check_nan)
    # print(collections.Counter(check_nan)[True])
    for index, boolen in enumerate(check_nan):
        if boolen == True:
            count += 1
    return count, collections.Counter(check_nan)[True], np.isnan(arr).sum()

def check_below_zero_in_x_arr(arr):
    # if np.min(arr) <= 0:
    #     return True
    # else:
    #     return False
    return np.min(arr)

# double check on x_arr values (nan)
for index, arr in enumerate(x_arr): # xy_cleaned_x_arr
    # check nan values left in x
    nan_count, nan_collections_count, isnan_count = check_nan_in_x_arr(arr)
    assert nan_count == nan_collections_count == isnan_count, "counting error! (%d - %d, %d, %d)" %(index, nan_count, nan_collections_count, isnan_count)
    assert nan_count == 0, "(%d, %d) there's stil nan in x_arr !" %(index, nan_count)
    # check below zero values left in x
    min_value = check_below_zero_in_x_arr(arr)
    assert min_value > 0, "(%d, %d) min value is below zero in array !"  %(index, min_value)
print("nan values - checked !")
print("values <= zero - checked !")

# double check on x_arr values (missing)
for index, arr in enumerate(x_arr): # xy_cleaned_x_arr
    # count, nans = check_nan_in_x_arr(arr)
    assert len(arr) == 3000, "(%d, %d) something's deleted !" %(index, len(arr))
# assert xy_cleaned_x_arr.shape == (len(xy_cleaned_x_arr), 3000), "something's deleted !"
print("all arrays with 3000 values - checked !")


nan values - checked !
values <= zero - checked !
all arrays with 3000 values - checked !


In [16]:
psutil.virtual_memory()

svmem(total=8499666944, available=1255878656, percent=85.2, used=7243788288, free=1255878656)

In [15]:
%who

arr	 c_arr	 case_mask	 case_mstds_list	 check_below_zero_in_x_arr	 check_nan_in_x_arr	 collections	 i	 idx	 
index	 isnan_count	 loaded_dataset	 min_value	 mstd_seg	 nan_collections_count	 nan_count	 np	 process_beat	 
psutil	 x_arr	 y_arr	 


### # split and save train/valid/test datas

In [17]:
# '''
# # train, valid, test split (caseid 기준)
# caseids = list(np.unique(c_arr))
# nvalid = max(1, int(len(caseids) * 0.4))
# ntest = max(1, int(len(caseids) * 0.2))

# caseids_train = caseids[nvalid:]
# caseids_valid = caseids[ntest:nvalid]
# caseids_test = caseids[:ntest]
# '''

import pickle

with open('D:/KAISTmicrodegree/5_캡스톤/플젝/[Microdegree] Hypotension/data_clf/clf_train_valid_test_caseids.pkl', 'rb') as f:
    caseids_train, caseids_valid, caseids_test = pickle.load(f)

caseids_total = caseids_train + caseids_valid + caseids_test # len(caseids_train)+len(caseids_valid)+len(caseids_test)

assert len(caseids_train) == len(set(caseids_train))
assert len(caseids_valid) == len(set(caseids_valid))
assert len(caseids_test) == len(set(caseids_test))
assert len(set(caseids_train) - set(caseids_valid)) == len(caseids_train)
assert len(set(caseids_train) - set(caseids_test)) == len(caseids_train)
assert len(set(caseids_valid) - set(caseids_train)) == len(caseids_valid)
assert len(set(caseids_valid) - set(caseids_test)) == len(caseids_valid)
assert len(set(caseids_test) - set(caseids_train)) == len(caseids_test)
assert len(set(caseids_test) - set(caseids_valid)) == len(caseids_test)

print(type(caseids_total), len(caseids_total), caseids_total)
print(type(caseids_train), len(caseids_train), caseids_train)
print(type(caseids_valid), len(caseids_valid), caseids_valid)
print(type(caseids_test), len(caseids_test), caseids_test)
print()

assert len(caseids_total) == len(caseids_train)+len(caseids_valid)+len(caseids_test)
print("Total caseids : ", len(caseids_total)) # caseids_total
print("- train caseids : ",  len(caseids_train), "(%.2f)" %(len(caseids_train)/len(caseids_total)*100)) # len(caseids_train)/caseids_total*100)
print("- valid caseids : ",  len(caseids_valid), "(%.2f)" %(len(caseids_valid)/len(caseids_total)*100)) # len(caseids_valid)/caseids_total*100
print("- test caseids : ",  len(caseids_test), "(%.2f)" %(len(caseids_test)/len(caseids_total)*100)) # len(caseids_test)/caseids_total*100

<class 'list'> 3327 [2539, 2542, 2544, 2547, 2548, 2549, 2553, 2558, 2559, 2561, 2562, 2566, 2568, 2569, 2572, 2573, 2575, 2576, 2578, 2580, 2583, 2584, 2585, 2587, 2589, 2590, 2593, 2594, 2596, 2597, 2601, 2602, 2604, 2605, 2607, 2609, 2611, 2612, 2613, 2616, 2618, 2619, 2622, 2624, 2628, 2630, 2631, 2632, 2636, 2637, 2639, 2641, 2644, 2645, 2646, 2648, 2651, 2652, 2655, 2656, 2657, 2658, 2662, 2663, 2664, 2665, 2667, 2670, 2671, 2672, 2673, 2674, 2676, 2677, 2678, 2680, 2687, 2688, 2690, 2693, 2695, 2697, 2698, 2699, 2701, 2702, 2703, 2705, 2706, 2712, 2713, 2716, 2717, 2720, 2721, 2724, 2727, 2731, 2732, 2733, 2735, 2736, 2740, 2741, 2742, 2744, 2746, 2747, 2749, 2750, 2751, 2752, 2753, 2755, 2760, 2762, 2763, 2764, 2765, 2766, 2769, 2774, 2775, 2776, 2777, 2778, 2779, 2781, 2783, 2785, 2788, 2795, 2799, 2800, 2801, 2803, 2804, 2806, 2807, 2808, 2809, 2812, 2815, 2819, 2820, 2823, 2824, 2827, 2828, 2829, 2830, 2835, 2836, 2839, 2845, 2847, 2848, 2849, 2850, 2851, 2854, 2857, 2858, 2

In [23]:
# train_mask = np.isin(c_arr, caseids_train).flatten()
# valid_mask = np.isin(c_arr, caseids_valid).flatten()
# test_mask = np.isin(c_arr, caseids_test).flatten()

# x_train = x_arr[train_mask]
# y_train = y_arr[train_mask]
# c_train = c_arr[train_mask]

# x_valid = x_arr[valid_mask]
# y_valid = y_arr[valid_mask]
# c_valid = c_arr[valid_mask]

# x_test = x_arr[test_mask]
# y_test = y_arr[test_mask]
# c_test = c_arr[test_mask]

total_data_by_id = {}
x_train, y_train, c_train = [], [], []
x_valid, y_valid, c_valid = [], [], []
x_test, y_test, c_test = [], [], []
excluded_count = 0

for index, id in enumerate(c_arr): # xy_cleaned_c_arr
    flag = False
    if id in caseids_train:
        x_train.append(x_arr[index]) # xy_cleaned_x_arr
        y_train.append(y_arr[index]) # xy_cleaned_y_arr
        c_train.append(id)
        flag = True
    elif id in caseids_valid:
        x_valid.append(x_arr[index]) # xy_cleaned_x_arr
        y_valid.append(y_arr[index]) # xy_cleaned_y_arr
        c_valid.append(id)
        flag = True
    elif id in caseids_test:
        x_test.append(x_arr[index]) # xy_cleaned_x_arr
        y_test.append(y_arr[index]) # xy_cleaned_y_arr
        c_test.append(id)
        flag = True
    else:
        excluded_count += 1

    if flag:
        if id not in total_data_by_id:
            total_data_by_id[id] = 0
        total_data_by_id[id] += 1

print("xy_cleaned_c_arr caseids : ", len(set(c_arr))) # xy_cleaned_c_arr
print("train/valid/test caseids : ", len(caseids_total)) # len(caseids_train)+len(caseids_valid)+len(caseids_test)
print("- xy_cleaned_c_arr - train/valid/test caseids : ", excluded_count)
print("- train/valid/test caseids - xy_cleaned_c_arr : ", len(set(caseids_total) - set(c_arr)), list(set(caseids_total) - set(c_arr))) # len(set(caseids_total) - set(xy_cleaned_c_arr)), list(set(caseids_total) - set(xy_cleaned_c_arr))
print()

# assert len(total_data_by_id.keys()) == len(caseids_train)+len(caseids_valid)+len(caseids_test), 'check id counts : {} != {} !'.format(len(total_data_by_id.keys()), len(caseids_train)+len(caseids_valid)+len(caseids_test))
assert len(total_data_by_id.keys()) == len(set(c_train))+len(set(c_valid))+len(set(c_test)), 'check id counts : {} != {} !'.format(len(total_data_by_id.keys()), len(set(c_train))+len(set(c_valid))+len(set(c_test)))
assert sum(total_data_by_id.values()) == len(x_train)+len(x_valid)+len(x_test), 'check data counts : {} != {} !'.format(sum(total_data_by_id.values()), len(x_train)+len(x_valid)+len(x_test))

print("(org) caseids train cnt: {}, caseids val cnt {}, caseids test cnt: {}".format(len(caseids_train), len(caseids_valid), len(caseids_test)))
print("(cleaned) caseids train cnt: {}, caseids val cnt {}, caseids test cnt: {}".format(len(set(c_train)), len(set(c_valid)), len(set(c_test))))

print("total ids : {}, total datas : {}".format(len(total_data_by_id.keys()), sum(total_data_by_id.values())))

print("- x train cnt: {}, x val cnt: {}, x test cnt: {}".format(len(x_train), len(y_train), len(c_train)), end=" ")
print("(%.2f)" %(len(x_train)/sum(total_data_by_id.values())*100))
print("- y train cnt: {}, y val cnt: {}, y test cnt: {}".format(len(x_valid), len(y_valid), len(c_valid)), end=" ")
print("(%.2f)" %(len(x_valid)/sum(total_data_by_id.values())*100))
print("- c train cnt: {}, c val cnt: {}, c test cnt: {}".format(len(x_test), len(y_test), len(c_test)), end=" ")
print("(%.2f)" %(len(x_test)/sum(total_data_by_id.values())*100))

xy_cleaned_c_arr caseids :  3256
train/valid/test caseids :  3327
- xy_cleaned_c_arr - train/valid/test caseids :  0
- train/valid/test caseids - xy_cleaned_c_arr :  71 [1408, 2432, 387, 2435, 2693, 1926, 2947, 4998, 521, 5253, 3980, 781, 2447, 3216, 1554, 3476, 4245, 6041, 4639, 2081, 6050, 3492, 1320, 2345, 2218, 6012, 3374, 2735, 2863, 4399, 1846, 4279, 1208, 5174, 2618, 1086, 6079, 1600, 3648, 5696, 1733, 6087, 1738, 587, 2379, 3918, 5454, 208, 3153, 6355, 3413, 599, 1367, 2775, 3799, 5721, 3167, 2400, 1505, 98, 4836, 1639, 5994, 1901, 2030, 881, 5362, 3323, 2428, 5501, 1023]

org : caseids train cnt: 1997, caseids val cnt 665, caseids test cnt: 665
cleaned : caseids train cnt: 1959, caseids val cnt 643, caseids test cnt: 654
total ids : 3256, total datas : 191453
- x train cnt: 117019, x val cnt: 117019, x test cnt: 117019 (61.12)
- y train cnt: 38148, y val cnt: 38148, y test cnt: 38148 (19.93)
- c train cnt: 36286, c val cnt: 36286, c test cnt: 36286 (18.95)


In [24]:
x_train = np.array(x_train)
y_train = np.array(y_train)
c_train = np.array(c_train)

x_valid = np.array(x_valid)
y_valid = np.array(y_valid)
c_valid = np.array(c_valid)

x_test = np.array(x_test)
y_test = np.array(y_test)
c_test = np.array(c_test)

print(x_train.shape, y_train.shape, c_train.shape)
print(x_valid.shape, y_valid.shape, c_valid.shape)
print(x_test.shape, y_test.shape, c_test.shape)

(117019, 3000) (117019,) (117019,)
(38148, 3000) (38148,) (38148,)
(36286, 3000) (36286,) (36286,)


In [25]:
## 0, 1 label 비중
import collections

train_zeros, valid_zeros, test_zeros = collections.Counter(y_train)[0], collections.Counter(y_valid)[0], collections.Counter(y_test)[0]
train_ones, valid_ones, test_ones = collections.Counter(y_train)[1], collections.Counter(y_valid)[1], collections.Counter(y_test)[1]
total_zeros = train_zeros + valid_zeros + test_zeros
total_ones = train_ones + valid_ones + test_ones

assert (total_zeros + total_ones) == sum(total_data_by_id.values()), "error in label counts !"
print("total 0 : %d" %(total_zeros))
print("- train : %d (%.2f), valid : %d (%.2f), test : %d (%.2f)" %(train_zeros, train_zeros/total_zeros*100, valid_zeros, valid_zeros/total_zeros*100, test_zeros, test_zeros/total_zeros*100))
print("total 1 : %d" %(total_ones))
print("- train : %d (%.2f), valid : %d (%.2f), test : %d (%.2f)" %(train_ones, train_ones/total_ones*100, valid_ones, valid_ones/total_ones*100, test_ones, test_ones/total_ones*100))


total 0 : 171263
- train : 104886 (61.24), valid : 34073 (19.90), test : 32304 (18.86)
total 1 : 20190
- train : 12133 (60.09), valid : 4075 (20.18), test : 3982 (19.72)


In [26]:
psutil.virtual_memory()

svmem(total=8499666944, available=1775906816, percent=79.1, used=6723760128, free=1775906816)

In [27]:
%who

arr	 c_arr	 c_test	 c_train	 c_valid	 case_mask	 case_mstds_list	 caseids_test	 caseids_total	 
caseids_train	 caseids_valid	 check_below_zero_in_x_arr	 check_nan_in_x_arr	 collections	 excluded_count	 f	 flag	 i	 
id	 idx	 index	 isnan_count	 loaded_dataset	 min_value	 mstd_seg	 nan_collections_count	 nan_count	 
np	 pickle	 process_beat	 psutil	 test_ones	 test_zeros	 total_data_by_id	 total_ones	 total_zeros	 
train_ones	 train_zeros	 valid_ones	 valid_zeros	 x_arr	 x_test	 x_train	 x_valid	 y_arr	 
y_test	 y_train	 y_valid	 


### # scale data for normalization

In [28]:
def scale_data(data): # ppg scale
    rng = np.nanmax(data) - np.nanmin(data)
    minimum = np.nanmin(data)
    data = (data - minimum) / rng
    return data

for i in range(len(x_train)):
    # x_train[i,0,:] = scale_data(x_train[i,0,:]) 
    # x_train[i] = np.array(scale_data(x_train[i]))
    x_train[i] = np.array(scale_data(x_train[i]))

for i in range(len(x_valid)):
    # x_valid[i,0,:] = scale_data(x_valid[i,0,:]) 
    # x_valid[i] = np.array(scale_data(x_valid[i]))
    x_valid[i] = scale_data(x_valid[i])

for i in range(len(x_test)):
    # x_test[i,0,:] = scale_data(x_test[i,0,:])
    # x_test[i] = np.array(scale_data(x_test[i]))
    x_test[i] = scale_data(x_test[i])

print(type(x_train), x_train.shape)
print(x_train[0])
print()
print(type(x_valid), x_valid.shape)
print(x_valid[0])
print()
print(type(x_test), x_test.shape)
print(x_test[0])

<class 'numpy.ndarray'> (117019, 3000)
[0.14814773 0.14814773 0.14814773 ... 0.41666645 0.48148182 0.56481422]

<class 'numpy.ndarray'> (38148, 3000)
[0.4000006  0.41250113 0.42500166 ... 0.59999928 0.58749887 0.57499834]

<class 'numpy.ndarray'> (36286, 3000)
[0.52174004 0.53623345 0.53623345 ... 0.65217694 0.60869672 0.56522027]


### # save data

In [32]:
with open('../data_clf/preprocess_ver3/train_clf_x.pkl', 'wb') as f:
    pickle.dump(x_train, f)
with open('../data_clf/preprocess_ver3/train_clf_y.pkl', 'wb') as f:
    pickle.dump(y_train, f)
with open('../data_clf/preprocess_ver3/train_clf_c.pkl', 'wb') as f:
    pickle.dump(c_train, f)

with open('../data_clf/preprocess_ver3/valid_clf_x.pkl', 'wb') as f:
    pickle.dump(x_valid, f)
with open('../data_clf/preprocess_ver3/valid_clf_y.pkl', 'wb') as f:
    pickle.dump(y_valid, f)
with open('../data_clf/preprocess_ver3/valid_clf_c.pkl', 'wb') as f:
    pickle.dump(c_valid, f)

with open('../data_clf/preprocess_ver3/test_clf_x.pkl', 'wb') as f:
    pickle.dump(x_test, f)
with open('../data_clf/preprocess_ver3/test_clf_y.pkl', 'wb') as f:
    pickle.dump(y_test, f)
with open('../data_clf/preprocess_ver3/test_clf_c.pkl', 'wb') as f:
    pickle.dump(c_test, f)

In [34]:
with open('../data_clf/preprocess_ver3/train_clf_x.pkl', 'rb') as f:
    train_x = pickle.load(f)
with open('../data_clf/preprocess_ver3/train_clf_y.pkl', 'rb') as f:
    train_y = pickle.load(f)
with open('../data_clf/preprocess_ver3/train_clf_c.pkl', 'rb') as f:
    train_c = pickle.load(f)
print(type(train_x), type(train_y), type(train_c))
# print(len(train_x), len(train_y), len(train_c))
print(train_x.shape, train_y.shape, train_c.shape)
print(len(train_x[0]), train_x[0])
print(train_y[:10])
print(train_c[:10])

print()
with open('../data_clf/preprocess_ver3/valid_clf_x.pkl', 'rb') as f:
    valid_x = pickle.load(f)
with open('../data_clf/preprocess_ver3/valid_clf_y.pkl', 'rb') as f:
    valid_y = pickle.load(f)
with open('../data_clf/preprocess_ver3/valid_clf_c.pkl', 'rb') as f:
    valid_c = pickle.load(f)
print(type(valid_x), type(valid_y), type(valid_c))
# print(len(valid_x), len(valid_y), len(valid_c))
print(valid_x.shape, valid_y.shape, valid_c.shape)
print(len(valid_x[0]), valid_x[0])
print(valid_y[:10])
print(valid_c[:10])

print()
with open('../data_clf/preprocess_ver3/test_clf_x.pkl', 'rb') as f:
    test_x = pickle.load(f)
with open('../data_clf/preprocess_ver3/test_clf_y.pkl', 'rb') as f:
    test_y = pickle.load(f)
with open('../data_clf/preprocess_ver3/test_clf_c.pkl', 'rb') as f:
    test_c = pickle.load(f)
print(type(test_x), type(test_y), type(test_c))
# print(len(test_x), len(test_y), len(test_c))
print(test_x.shape, test_y.shape, test_c.shape)
print(len(test_x[0]), test_x[0])
print(test_y[:10])
print(test_c[:10])

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
(117019, 3000) (117019,) (117019,)
3000 [0.14814773 0.14814773 0.14814773 ... 0.41666645 0.48148182 0.56481422]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[3681 3681 3681 3681 3681 3681 3681 3681 3681 3681]

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
(38148, 3000) (38148,) (38148,)
3000 [0.4000006  0.41250113 0.42500166 ... 0.59999928 0.58749887 0.57499834]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2283 2283 2283 2283 2283 2283 2283 2283 2283 2283]

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
(36286, 3000) (36286,) (36286,)
3000 [0.52174004 0.53623345 0.53623345 ... 0.65217694 0.60869672 0.56522027]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[969 969 969 969 969 969 969 969 969 969]
